### ISSUE TITLE
WGI Indicator Dataset

### ISSUE THREAD

**Issue by ryanritchey** [Nosferican/WorldBankDataDive2019ConflictSpendingAsia#3]
[wgidataset.xlsx](https://github.com/Nosferican/WorldBankDataDive2019ConflictSpendingAsia/files/3699518/wgidataset.xlsx)

**Comment by nbroekman** [comment]
Indicators:

https://data.worldbank.org/indicator/DT.ODA.ODAT.GN.ZS

**Comment by Nosferican** [comment]
Closed by #5.
